language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_script:
  - npm run build-css
script:
  - npm test
  - npm run build

deploy:
  provider: script
  script: deploy.sh $TRAVIS_TAG
